<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace {namespace}\servant;

use kuiper\tars\annotation\TarsParameter;
use kuiper\tars\annotation\TarsReturnType;
use kuiper\tars\annotation\TarsServant;

/**
 * @TarsServant("HelloObj")
 */
interface HelloServant
{
    /**
     * @TarsParameter(name="message", type="string")
     * @TarsReturnType("string")
     *
     * @param string $message
     *
     * @return string
     */
    public function hello(string $message): string;
}
