<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 0.6
 */

namespace {namespace}\servant;

use kuiper\jsonrpc\attribute\JsonRpcService;

#[JsonRpcService(service: "HelloObj")]
interface HelloServant
{
    public function say(string $message): string;

}
