<?php

declare(strict_types=1);

/**
 * NOTE: This class is auto generated by Tars Generator (https://github.com/wenbinye/tars-generator).
 *
 * Do not edit the class manually.
 * Tars Generator version: 1.0
 */

namespace {namespace}\servant;

use kuiper\tars\attribute\TarsParameter;
use kuiper\tars\attribute\TarsReturnType;
use kuiper\tars\attribute\TarsServant;

#[TarsServant("HelloObj")]
interface HelloServant
{
    #[TarsReturnType("string")]
    public function say(#[TarsParameter(type: "string")] string $message): string;
}
